USE `15_colonial_blog_db`;
--
INSERT INTO `users` (`id`, `username`, `password`, `email`)
VALUES (1, 'UnderSinduxrein', '4l8nYGTKMW', 'azfex@gmail.com'),
       (2, 'BlaAntigadsa', ':Q5wjT4e', 'kuf@abv.bg'),
       (3, 'ANinedsa', 'ElMwhxY)J', 'indie@yahoo.com'),
       (4, 'ScoreImmagidefon', '`NGU>oS', 'daffy@yandex.bg'),
       (5, 'BlaSinduxrein', 'wJyfcwg*', 'toni@donald.eu'),
       (6, 'WhoDenoteBel', 'ajmISQi*', 'tinny@pd.cd'),
       (7, 'WhatTerrorBel', 'R+-<+..Pl3j^', 'joseph@lon.co.uk'),
       (8, 'AryaDenotehow', 'NNY5<e=', 'corect@asd.asd'),
       (9, 'UnveiledDenoteIana', 'no0*ijt', 'default@ooo.com'),
       (10, 'ScoreSinduxIana', '8xI:@-j2_.T', 'rog@asus.co'),
       (11, 'RoundAntigaBel', '4S>7EUNeUC@kv', 'diplomat@po.bo'),
       (12, 'DarkImmagidsa', 'R.fhf1Zh>2', 'sys@admin.bg'),
       (13, 'RoundInspecindi', 'AdKs>qu7P`C', 'katr@kiper.eu'),
       (14, 'AryaNinehow', 'X6j>`Huf2F(I', 'wrec@soft.wrap'),
       (15, 'ScoreAntigarein', 'UUD3H))<', 'dec@int.float'),
       (16, 'TheDivineBel', '-gCi:_Ub?ypT', 'rindiy@abv.bg'),
       (17, 'RoundArmydsa', 'SZ?F-:hW', 'com@gmail.user'),
       (18, 'HighAsmahow', 'lyqF\vUG', 'svik@kiwi.mandarin'),
       (19, 'ZendArmyhow', 'DbW>9,', 'rip@pob.cid'),
       (20, 'BlaImmagiIana', 'upE;fg6+)n', 'stun@asd.cdd');

INSERT INTO `categories` (`id`, `category`)
VALUES (1, 'Nature'),
       (2, 'Animals'),
       (3, 'Historical'),
       (4, 'Geography'),
       (5, 'Social');

INSERT INTO `articles` (`id`, `title`, `content`, `category_id`)
VALUES (1, 'John Hyrcanus',
        'John Hyrcanus was a Hasmonean (Maccabeean) leader and Jewish high priest of the 2nd century BCE (born 164 BCE, reigned from 134 BCE until his death in 104 BCE). In rabbinic literature he is often referred to by the epithet, Yo?anan Cohen Gadol .',
        3),
       (2, 'Donnybrook, Victoria',
        'Donnybrook is a suburb of Melbourne, Victoria, Australia, 32 km north of Melbourne''s Central Business District, located within the City of Whittlesea. It is bounded to the west by Merri Creek and in the east by Darebin Creek. At the 2016 Census, Donnybrook had a population of 169. The town consists of a railway station, general store, pub, spa and a small number of houses.',
        4),
       (3, 'Denmark in the Eurovision Song Contest 1988',
        'Denmark was represented by Hot Eyes (the name chosen for use at Eurovision by Kirsten & Soren), with the song ''"Ka'' du se hva'' jeg sa''?", at the 1988 Eurovision Song Contest, which took place on 30 April in Dublin. "Ka'' du se hva'' jeg sa''?" was chosen as the Danish entry at the Dansk Melodi Grand Prix on 27 February. This was the last of three Eurovision appearances for Kirsten & Soren.',
        5),
       (4, 'Sihora', 'Sihora is a town and a municipality in Jabalpur district in the Indian state of Madhya Pradesh.',
        4),
       (5, 'HMS Safari (P211)',
        'HMS Safari, launched in November 1941, was one of the third group of British S-class submarines built by Cammell Laird & Co Limited, Birkenhead. So far she has been the only ship to bear the name Safari.',
        3),
       (6, 'Richard Purcell (architect)',
        'Richard Purcell was an Irish architect and builder active in mid-nineteenth-century County Wexford, in the southeast of Ireland. He was associated with the Day family of architects, which included Martin Day, William Day, John Day.',
        3),
       (7, 'Grand Hotel Kempinski High Tatras',
        'The Grand Hotel Kempinski High Tatras is a five-star hotel operated by Kempinski Hotels S.A. located on the shores of Strbske pleso (Tschirmer See) in High Tatras, Slovakia.',
        4),
       (8, 'Song Sung Blue (album)',
        'Song Sung Blue is an album by American pop singer Johnny Mathis that was released on September 13, 1972,1 by Columbia Records and featured his renditions of mostly recent chart hits.',
        5),
       (9, 'Dotted galliwasp',
        'The dotted galliwasp or Malpelo galliwasp (Diploglossus millepunctatus) is a carnivorous species of lizard found only on Malpelo Island, Colombia.',
        2),
       (10, 'Mycosphaerella graminicola',
        'Mycosphaerella graminicola. Synonym: Septoria tritici. Correct taxonomic name: Zymoseptoria tritici, is a species of filamentous fungus, an ascomycete in the family Mycosphaerellaceae. It is a wheat plant pathogen causing septoria leaf blotch that is difficult to control due to resistance to multiple fungicides. The pathogen today causes one of the most important diseases of wheat.',
        1),
       (11, 'History of the Royal Naval Reserve',
        'The Royal Naval Reserve are a part of the Royal Navy of the United Kingdom.', 3),
       (12, '1st Rank Raju',
        '1st Rank Raju is a 2015 Indian Kannada comedy drama film written and directed by Naresh Kumar HN in his debut, and produced by V. K. Manjunath. It features Gurunandan and Apoorva Gowda in the lead roles. The rest of the cast includes Tanishka Kapoor, Sadhu Kokila, Ananth Nag, Achyut Rao, Manadeep Rai, Giri Mahesh and Master Chinmai. The film''s music director Kiran Ravindranath.',
        5),
       (13, 'Large White Ulster pig',
        'The Large White Ulster, or Ulster White, was a breed of domestic pig. Primarily bred for bacon production, it was the favoured breed of farmers in the north of Ireland up until the mid 20th century.',
        2),
       (14, 'Penicillium brunneum',
        'Penicillium brunneum is an anamorph fungus species of the genus of Penicillium which was isolated in imported rice an produces rugulosin a substance which is hepatocarcinogenic to mice and rats.',
        1),
       (15, 'Napana Hunuangegammedda',
        'Napana Hunuangegammedda is a village in Sri Lanka. It is located within Central Province.', 4),
       (16, 'She Wants Revenge',
        'She Wants Revenge is an American rock band, based in San Fernando Valley, California and formed in 2004. The group''s debut album She Wants Revenge was released in early 2006, with three singles to follow ("These Things," a video featuring Shirley Manson from Garbage, "Out of Control," and "Tear You Apart" for which the video was directed by Joaquin Phoenix). The band has sold more than 300,000 records in the US. The band''s second album, This Is Forever, was released in 2007. The group''s third album, entitled Valleyheart, was released in 2011.',
        5),
       (17, 'Martin Henriksson',
        'Hans Martin Knut Henriksson (born 30 October 1974) is a former Swedish musician best known for his work with death metal band Dark Tranquillity and was one of the original members, and the main songwriter for the band until he left them in 2015.',
        5),
       (18, 'Jan-Emmanuel De Neve',
        'Jan-Emmanuel De Neve (born 14 March 1979) is a Belgian economist and professor at the University of Oxford. He is best known for his research on the economics of happiness12 which has led to new insights into the relationship between happiness and income,3 productivity,4 economic growth,56 and inequality.7 His research was selected among "The Management Ideas that Mattered Most in 2016" by Harvard Business Review8 and he was awarded the Ruut Veenhoven Award in 2015 for his contributions to the scientific study of happiness.9',
        5),
       (19, 'Miller Building (Liberty, Missouri)',
        'Miller Building is a historic commercial building located at Liberty, Clay County, Missouri. It was built in 1868, and is a two-story, rectangular brick building with Late Victorian style design elements. It has a flat roof and features a decorative brick cornice, hooded window surrounds, and an intact storefront with cast-iron columns.',
        4),
       (20, 'St. Matthew''s German Evangelical Lutheran Church',
        'The German Evangelical Lutheran Church of Charleston, South Carolina, was incorporated on December 3, 1840. Through usage and custom the Church is now known as St. Matthew''s German Evangelical Lutheran Church or St. Matthew''s Lutheran Church and is a member of the South Carolina Synod of the Evangelical Lutheran Church in America.',
        4),
       (21, 'Ceropales elegans',
        'Ceropales elegans is a spider wasp species in the genus Ceropales. It is found in Texas.', 1),
       (22, 'Normandy Grange',
        'Normandy Grange is located along NY 9D north of Garrison, New York, United States. It is a Norman-style house and farm complex built in the early 20th century.',
        3),
       (23, 'Montana gubernatorial election, 1988',
        'The 1988 Montana gubernatorial election took place on November 8, 1988. Incumbent Governor of Montana Ted Schwinden, who was first elected in 1980 and was re-elected in 1984, declined to seek re-election to a third term, creating an open seat. Stan Stephens, the former President of the Montana Senate, won a close Republican primary, and advanced to the general election, where he was opposed by Thomas Lee Judge, Schwinden''s predecessor as governor and the Democratic nominee. Though the general election was hotly contested, Stephens ultimately defeated Judge, becoming the first Republican to win a gubernatorial election in Montana since 1964.',
        5),
       (24, 'Nimbochromis livingstonii',
        'Nimbochromis livingstonii, Livingston''s cichlid or (locally) kalingono, is a freshwater mouthbrooding cichlid native to Lake Malawi, an African Rift Lake. It is also found in the upper Shire River and Lake Malombe. They are found in inshore areas of the lake over sandy substrates.',
        2),
       (25, 'Moore''s frog',
        'Moore''s frog, Lithobates johni, is a frog species in the true frog family (Ranidae). It is endemic to Mexico, where it is known as rana de Moore after its obsolete scientific name, which had already been given to an unrelated fossil frog species earlier.',
        2),
       (26, 'P. T. Rajan',
        'Sir Ponnambala Thiaga Rajan (12 April 1892 – 25 September 1974) was the Chief Minister of Madras Presidency from 4 April 1936, to 24 August 1936. He was also the last President of the Justice Party.',
        3),
       (27, 'Jackie Torrens',
        'Jackie Torrens (born in Prince Edward Island) is a Canadian award-winning writer, actress, documentary-maker and journalist, best known for her CBC radio and television appearances, and for acting roles in the television series Made in Canada the OUTtv mini-series, Sex & Violence and Andrea Dorfman''s feature film Heartbeat. With producer Jessica Brown, she is a co-partner in Peep Media Inc. Their documentaries include Edge of East, My Week On Welfare (Screen Nova Scotia nominees for Best Documentary) & Small Town Show Biz: 2 Dreams From A Harbourtown (Yorkton Film Fest nominee Best Arts & Culture Doc), all broadcast on CBC & the Documentary Channel. Their latest doc, Bernie Langille Wants To Know Who Killed Bernie Langille, is for Bravofactual and examines the mysterious death of a military electrician in 1968. Her docs for Telltale Productions include Free Reins for CBC''s POV Docs (Yorkton Film Fest Best POV Doc nominee) and the upcoming feature doc Radical Age. All documentaries are directed & written by Jackie Torrens. "Torrens has a new documentary...bizarre, funny and incredibly moving..." Shameless Magazine',
        5),
       (28, 'Garner, Boyd County, Kentucky',
        'Garner is an unincorporated community in Boyd County, Kentucky, United States. Garner is located on Pigeon Roost Creek at the junction of Kentucky Route 854 and Kentucky Route 1945, 10.6 miles (17.1 km) southwest of Catlettsburg.',
        4),
       (29, 'Incurvaria pectinea', 'Incurvaria pectinea is a moth of the family Incurvariidae. It is found in Europe.',
        1),
       (30, 'Navia steyermarkii',
        'Navia steyermarkii is a species in the genus Navia. This species is endemic to Venezuela.', 1),
       (31, 'Shaggy parasol',
        'Shaggy parasol is the common name for three closely related species of mushroom, Chlorophyllum rhacodes (or rachodes), C. olivieri and C. brunneum, found in North America, Europe and Southern Africa (the latter species is also found in Australia).',
        1),
       (32, 'Metropolitan Police Clubs and Vice Unit',
        'The Clubs & Vice Unit was an Operational Command Unit of London''s Metropolitan Police which provides advice and practical support to other units in the Metropolitan Police concerning the policing of nightclubs, vice and obscene publications.',
        5),
       (33, 'Ignatius Carbonnelle',
        'Ignatius Carbonnelle (1829–1889 was a Jesuit, mathematician and the founder of the Scientific Society of Brussels.',
        3),
       (34, 'Unxia laeta',
        'Unxia laeta is a species of beetle in the family Cerambycidae. It was described by Felix Edouard Guerin-Meneville in 1844.',
        1),
       (35, 'Peters''s sheath-tailed bat',
        'Peters''s sheath-tailed bat (Paremballonura atrata) is a species of sac-winged bat in the family Emballonuridae. It is found only in Madagascar. It is threatened by habitat loss.',
        2),
       (36, 'DELETE THIS', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. ', null);

INSERT INTO `users_articles` (`article_id`, `user_id`)
VALUES (2, 15),
       (26, 16),
       (30, 2),
       (16, 11),
       (10, 15),
       (28, 17),
       (7, 19),
       (22, 3),
       (16, 4),
       (25, 15),
       (18, 5),
       (30, 17),
       (1, 14),
       (1, 1),
       (27, 1),
       (12, 2),
       (2, 16),
       (16, 18),
       (33, 12),
       (30, 1),
       (15, 17),
       (3, 1),
       (14, 4),
       (28, 16),
       (24, 15),
       (29, 3),
       (32, 19),
       (3, 14),
       (10, 2),
       (13, 15),
       (7, 1),
       (15, 9),
       (22, 5),
       (5, 9),
       (32, 16),
       (25, 6),
       (9, 13),
       (29, 15),
       (33, 14),
       (9, 9),
       (3, 3),
       (22, 4),
       (8, 5),
       (21, 13),
       (29, 5),
       (5, 2),
       (22, 10),
       (2, 1),
       (10, 19),
       (17, 4),
       (7, 7),
       (20, 6),
       (11, 1),
       (18, 16),
       (23, 18),
       (32, 14),
       (28, 13),
       (29, 6),
       (14, 7),
       (1, 18),
       (1, 10),
       (26, 1),
       (5, 12),
       (34, 17),
       (21, 3),
       (8, 16),
       (31, 13),
       (13, 1),
       (14, 8),
       (13, 9),
       (1, 6),
       (32, 8),
       (25, 12),
       (19, 15),
       (30, 12),
       (30, 11),
       (2, 3),
       (24, 1),
       (22, 9),
       (34, 14),
       (31, 16),
       (11, 7),
       (27, 10),
       (6, 1),
       (31, 1),
       (4, 14),
       (30, 19),
       (6, 15),
       (16, 2),
       (10, 3),
       (3, 17),
       (9, 5),
       (13, 7),
       (7, 6),
       (22, 8),
       (23, 19),
       (26, 11),
       (3, 7),
       (33, 1),
       (27, 2);

INSERT INTO `comments` (`id`, `comment`, `article_id`, `user_id`)
VALUES (1, 'cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus', 20, 20),
       (2, 'integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula', 2, 12),
       (3, 'duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi', 2, 17),
       (4, 'sed accumsan felis ut at dolor quis odio consequat varius integer ac leo', 3, 9),
       (5, 'in tempus sit amet sem fusce consequat nulla nisl nunc nisl', 7, 19),
       (6, 'nam congue risus semper porta volutpat quam pede lobortis ligula sit amet', 22, 14),
       (7, 'natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis', 29,
        6),
       (8, 'maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta', 24, 8),
       (9, 'risus auctor sed tristique in tempus sit amet sem fusce consequat', 5, 1),
       (10, 'porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus', 16, 15),
       (11, 'at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at', 30, 18),
       (12, 'at velit eu est congue elementum in hac habitasse platea', 34, 17),
       (13,
        'metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec',
        9, 10),
       (14, 'enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris', 9, 16),
       (15, 'in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat', 32, 19),
       (16, 'etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut', 22, 16),
       (17, 'nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus', 9,
        16),
       (18, 'justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis', 33, 14),
       (19, 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae', 8, 11),
       (20, 'id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus', 31, 4),
       (21, 'justo sollicitudin ut suscipit a feugiat et eros vestibulum ac', 2, 17),
       (22, 'malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor', 9, 5),
       (23, 'sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at', 31, 13),
       (24, 'nisl nunc rhoncus dui vel sem sed sagittis nam congue', 19, 10),
       (25, 'lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in', 32, 11),
       (26, 'turpis enim blandit mi in porttitor pede justo eu massa donec', 26, 15),
       (27, 'lectus pellentesque eget nunc donec quis orci eget orci vehicula', 34, 6),
       (28, 'mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu', 21, 5),
       (29, 'est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam', 32,
        18),
       (30, 'magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia', 5, 1),
       (31, 'ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero', 31, 10),
       (32, 'tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis', 6, 19),
       (33, 'amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus', 35,
        18),
       (34, 'justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut', 21, 18),
       (35, 'a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus', 1, 17),
       (36, 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel', 30, 11),
       (37, 'sit amet lobortis sapien sapien non mi integer ac neque duis bibendum', 31, 20),
       (38, 'integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel', 15, 13),
       (39, 'pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim', 21, 16),
       (41, 'est phasellus sit amet erat nulla tempus vivamus in felis eu sapien', 31, 9),
       (42, 'nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis', 25, 6),
       (43, 'leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede', 10, 12),
       (44, 'ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc', 9, 18),
       (45, 'odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac', 30, 19),
       (46, 'quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id', 5, 7),
       (47,
        'vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum', 3,
        16),
       (48, 'platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id', 5, 7),
       (49, 'mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate', 26, 12),
       (50, 'neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet', 27, 7),
       (51, 'rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia', 32, 8),
       (52, 'in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit', 22, 13),
       (53, 'sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt', 2, 10),
       (54, 'vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor', 27, 14),
       (55, 'dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum', 18, 10),
       (56, 'quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis',
        21, 16),
       (57, 'vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer',
        23, 16),
       (58, 'sapien sapien non mi integer ac neque duis bibendum morbi', 33, 14),
       (59, 'proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut', 27, 20),
       (60, 'ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla', 13, 12),
       (61, 'sapien non mi integer ac neque duis bibendum morbi non quam', 5, 4),
       (62, 'arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium', 19, 15),
       (63, 'sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis', 31, 17),
       (64, 'dui vel sem sed sagittis nam congue risus semper porta volutpat', 28, 11),
       (65, 'quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis', 12, 11),
       (66, 'duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis', 11, 9),
       (67, 'sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut', 34, 11),
       (68, 'sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id',
        23, 14),
       (69, 'massa id nisl venenatis lacinia aenean sit amet justo morbi', 21, 20),
       (70, 'nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum', 2,
        20),
       (71,
        'ipsum dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius',
        20, 9),
       (72, 'cursus urna ut tellus nulla ut erat id mauris vulputate', 8, 14),
       (73, 'id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat', 29, 4),
       (74, 'tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet', 31, 18),
       (75, 'rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio', 6, 6);

INSERT INTO `likes` (`id`, `article_id`, `comment_id`, `user_id`)
VALUES (1, NULL, 65, 19),
       (2, 35, NULL, 11),
       (3, NULL, 19, 10),
       (4, 25, NULL, 13),
       (5, NULL, 13, 18),
       (6, 30, NULL, 8),
       (7, NULL, 13, 19),
       (8, NULL, 70, 14),
       (9, 33, NULL, 11),
       (10, NULL, 50, 9),
       (11, 30, NULL, 12),
       (12, NULL, 2, 13),
       (13, 30, NULL, 17),
       (14, NULL, 58, 9),
       (15, 33, NULL, 16),
       (16, NULL, 16, 13),
       (17, 19, NULL, 7),
       (18, NULL, 61, 11),
       (19, 8, NULL, 8),
       (20, NULL, 41, 6),
       (21, 35, NULL, 8),
       (22, NULL, 60, 10),
       (23, 30, NULL, 17),
       (24, NULL, 64, 14),
       (26, NULL, 18, 7),
       (27, 19, NULL, 20),
       (28, NULL, 21, 19),
       (29, 6, NULL, 12),
       (30, NULL, 30, 12),
       (31, 35, NULL, 9),
       (32, NULL, 63, 6),
       (33, 2, NULL, 9),
       (34, NULL, 68, 14),
       (35, 24, NULL, 18),
       (36, NULL, 75, 15),
       (37, 3, NULL, 4),
       (38, NULL, 57, 18),
       (39, 25, NULL, 2),
       (40, NULL, 20, 18),
       (41, 25, NULL, 16),
       (42, NULL, 44, 13),
       (43, 18, NULL, 16),
       (44, NULL, 75, 11),
       (45, 29, NULL, 11),
       (46, NULL, 63, 15),
       (47, 22, NULL, 4),
       (48, NULL, 66, 12),
       (49, 1, NULL, 16),
       (50, NULL, 69, 7);